Feature branch: Portfolio Setup and Mobile Version Skeleton
abenezer-addisu/Portfolio-Setup-and-mobile-version-skeleton pull request #1
Opened 2023-03-23 19:19 UTC by abenezer-addisu

In This Branch i did the following:

- Add HTML and CSS file 
- Mobile First Responsive 
- Add Linters file 
- Edit Readme file

2023-03-23 20:11 UTC, binhussen requested changes
Hi @abenezer-addisu  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 20:11 UTC, binhussen commented on index.html
> +    <div class="home-page">
- Great job for using semantic tags, I think the `div` tag is not usable to wrap the header and section, the `div` used only for unknown elements, so please remove it for better sematic reasons :+1:

2023-03-23 20:11 UTC, binhussen commented on CSS/style.css
> +}
- Kindly, Use the Exact margins (top, bottom, left, right) and colors `#172B4D` defined for the template to have better design :+1: 

| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img src="https://user-images.githubusercontent.com/52010789/227338891-343e94ea-ef7c-4ac0-a276-7e53c304ff5a.png" width="200">|<img src="https://user-images.githubusercontent.com/52010789/227338882-9ff1e05b-7124-41a7-b46b-3dc0b51346af.png" width="200">|

![2023-03-23_22-50](https://user-images.githubusercontent.com/52010789/227338878-b3e17f32-ec5b-4abc-a3a4-cbbef866bdb8.png)
😎️

2023-03-24 19:04 UTC, frank1738 reviewed
Hi @abenezer-addisu , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

-  [ ] You have submitted a project with failing linter checks. Kindly fix them and resubmit your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-24 19:26 UTC, frank1738 approved these changes
Hi @abenezer-addisu , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/11ISwbgCxEzMyY/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ Good documentation

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 19:30 UTC, merged